GET http://localhost:8080/todos HTTP/1.1

###

POST http://localhost:8080/todos HTTP/1.1
Content-Type: application/json

{
    "todo":"tetete",
    "status":"not done"
}

###

PUT http://localhost:8080/todos/a0d4 HTTP/1.1
Content-Type: application/json

{
    "todo":"totototo",
    "status":"halfwayy"
}

###
GET http://localhost:8080/todos/846b082e-a0d4-492f-83b9-ea12bc1a8d3a HTTP/1.1


###
DELETE http://localhost:8080/todos/846b082e-a0d4-492f-83b9-ea12bc1a8d3a HTTP/1.1