GET http://localhost:8080/todos HTTP/1.1

###

POST http://localhost:8080/todos HTTP/1.1
Content-Type: application/json

{
    "todo":"tetete",
    "status":"not done"
}

###

PUT http://localhost:8080/todos/5 HTTP/1.1
Content-Type: application/json

{
    "todo":"totototo",
    "status":"halfwayy"
}

###
GET http://localhost:8080/todos/2 HTTP/1.1


###
DELETE http://localhost:8080/todos/2 HTTP/1.1